parameters:
    didweb_resize.acciones.class: Didweb\Bundle\ResizeBundle\Acciones\Resize

services:
    didweb_resize.acciones:
        class: %didweb_resize.acciones.class%
        arguments: [ @service_container ]
